-- Migration Script for GAP-NEW-008 (RFC-013 Unified Confidence Model)
-- Execute this script in the Supabase SQL Editor

ALTER TABLE verification_audit_logs 
ADD COLUMN IF NOT EXISTS confidence_score SMALLINT 
CHECK (confidence_score >= 0 AND confidence_score <= 100);

COMMENT ON COLUMN verification_audit_logs.confidence_score IS 'Evidence Confidence Score (0-100) generated by ConfidenceEngine (RFC-013)';
